import { useState } from "react";

export default function Alerts() {
  const [filter, setFilter] = useState("ALL");

  // Temporary development data.
  // Later this will come from the backend API.
  const [alerts] = useState([
    {
      id: 1,
      timestamp: "10:42:18",
      severity: "CRITICAL",
      message: "Backend error rate increased",
      source: "Backend",
      status: "ACTIVE",
    },
    {
      id: 2,
      timestamp: "10:40:05",
      severity: "WARNING",
      message: "Queue above 40,000 users",
      source: "Waiting Room",
      status: "ACTIVE",
    },
    {
      id: 3,
      timestamp: "10:37:42",
      severity: "WARNING",
      message: "Inventory almost sold out",
      source: "Inventory",
      status: "ACTIVE",
    },
    {
      id: 4,
      timestamp: "10:32:16",
      severity: "INFO",
      message: "Sale started",
      source: "Events",
      status: "RESOLVED",
    },
    {
      id: 5,
      timestamp: "10:28:54",
      severity: "INFO",
      message: "Admission rate updated to 200 users/batch",
      source: "Admission Control",
      status: "RESOLVED",
    },
    {
      id: 6,
      timestamp: "10:25:31",
      severity: "WARNING",
      message: "Backend load reached 72%",
      source: "System",
      status: "RESOLVED",
    },
  ]);

  const filteredAlerts =
    filter === "ALL"
      ? alerts
      : alerts.filter((alert) => alert.severity === filter);

  const criticalCount = alerts.filter(
    (alert) => alert.severity === "CRITICAL"
  ).length;

  const warningCount = alerts.filter(
    (alert) => alert.severity === "WARNING"
  ).length;

  const infoCount = alerts.filter(
    (alert) => alert.severity === "INFO"
  ).length;

  return (
    <div style={styles.page}>
      {/* Header */}
      <div style={styles.header}>
        <div>
          <p style={styles.overline}>FAIRQUEUE ADMIN</p>

          <h1 style={styles.title}>Alerts</h1>

          <p style={styles.subtitle}>
            Monitor important events and system conditions.
          </p>
        </div>

        <div style={styles.liveBadge}>
          <span style={styles.liveDot}></span>
          LIVE MONITORING
        </div>
      </div>

      {/* Alert Summary */}
      <div style={styles.summaryGrid}>
        <SummaryCard
          label="CRITICAL"
          value={criticalCount}
          description="Immediate attention"
          type="critical"
        />

        <SummaryCard
          label="WARNING"
          value={warningCount}
          description="Needs monitoring"
          type="warning"
        />

        <SummaryCard
          label="INFO"
          value={infoCount}
          description="System information"
          type="info"
        />

        <SummaryCard
          label="TOTAL ALERTS"
          value={alerts.length}
          description="All recorded alerts"
          type="total"
        />
      </div>

      {/* Main Alert Panel */}
      <div style={styles.panel}>
        {/* Panel Header */}
        <div style={styles.panelHeader}>
          <div>
            <h2 style={styles.panelTitle}>System Alerts</h2>

            <p style={styles.panelDescription}>
              Recent alerts generated by the FairQueue system.
            </p>
          </div>

          {/* Filters */}
          <div style={styles.filters}>
            {["ALL", "CRITICAL", "WARNING", "INFO"].map((item) => (
              <button
                key={item}
                onClick={() => setFilter(item)}
                style={{
                  ...styles.filterButton,
                  ...(filter === item
                    ? styles.activeFilter
                    : {}),
                }}
              >
                {item}
              </button>
            ))}
          </div>
        </div>

        {/* Alerts Table */}
        <div style={styles.tableContainer}>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th}>TIME</th>
                <th style={styles.th}>SEVERITY</th>
                <th style={styles.th}>MESSAGE</th>
                <th style={styles.th}>SOURCE</th>
                <th style={styles.th}>STATUS</th>
              </tr>
            </thead>

            <tbody>
              {filteredAlerts.length > 0 ? (
                filteredAlerts.map((alert) => (
                  <tr key={alert.id} style={styles.tableRow}>
                    <td style={styles.td}>
                      <span style={styles.time}>
                        {alert.timestamp}
                      </span>
                    </td>

                    <td style={styles.td}>
                      <SeverityBadge severity={alert.severity} />
                    </td>

                    <td style={styles.td}>
                      <div style={styles.message}>
                        {alert.message}
                      </div>
                    </td>

                    <td style={styles.td}>
                      <span style={styles.source}>
                        {alert.source}
                      </span>
                    </td>

                    <td style={styles.td}>
                      <StatusBadge status={alert.status} />
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="5" style={styles.emptyState}>
                    No alerts found for this filter.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Recent Critical Events */}
      <div style={styles.bottomGrid}>
        <div style={styles.activityCard}>
          <div style={styles.cardHeader}>
            <div>
              <h2 style={styles.cardTitle}>
                Critical Events
              </h2>

              <p style={styles.cardDescription}>
                Alerts requiring immediate attention.
              </p>
            </div>

            <div style={styles.criticalIcon}>!</div>
          </div>

          {alerts
            .filter((alert) => alert.severity === "CRITICAL")
            .map((alert) => (
              <div key={alert.id} style={styles.criticalEvent}>
                <div style={styles.eventDot}></div>

                <div>
                  <strong style={styles.eventMessage}>
                    {alert.message}
                  </strong>

                  <p style={styles.eventMeta}>
                    {alert.timestamp} · {alert.source}
                  </p>
                </div>
              </div>
            ))}

          {criticalCount === 0 && (
            <p style={styles.noCritical}>
              No critical alerts.
            </p>
          )}
        </div>

        {/* Alert Rules */}
        <div style={styles.activityCard}>
          <div style={styles.cardHeader}>
            <div>
              <h2 style={styles.cardTitle}>
                Alert Conditions
              </h2>

              <p style={styles.cardDescription}>
                Conditions monitored by the system.
              </p>
            </div>
          </div>

          <AlertRule
            title="Queue Threshold"
            description="Queue exceeds configured limit"
            severity="WARNING"
          />

          <AlertRule
            title="Backend Error Rate"
            description="Backend errors increase above threshold"
            severity="CRITICAL"
          />

          <AlertRule
            title="Inventory Threshold"
            description="Available inventory becomes low"
            severity="WARNING"
          />

          <AlertRule
            title="Inventory Consistency"
            description="Inventory state becomes inconsistent"
            severity="CRITICAL"
          />
        </div>
      </div>

      {/* Information */}
      <div style={styles.infoBox}>
        <div style={styles.infoIcon}>i</div>

        <div>
          <h3 style={styles.infoTitle}>
            Real-time alert monitoring
          </h3>

          <p style={styles.infoText}>
            In the final system, alerts should be generated by
            backend monitoring services and delivered to the Admin
            Dashboard through REST APIs and real-time events.
          </p>
        </div>
      </div>
    </div>
  );
}

/* =========================================================
   SUMMARY CARD
========================================================= */

function SummaryCard({
  label,
  value,
  description,
  type,
}) {
  const typeStyles = {
    critical: {
      background: "#fef2f2",
      color: "#b91c1c",
      icon: "!",
    },

    warning: {
      background: "#fffbeb",
      color: "#a16207",
      icon: "!",
    },

    info: {
      background: "#eff6ff",
      color: "#1d4ed8",
      icon: "i",
    },

    total: {
      background: "#f8fafc",
      color: "#475569",
      icon: "•",
    },
  };

  const current = typeStyles[type];

  return (
    <div style={styles.summaryCard}>
      <div
        style={{
          ...styles.summaryIcon,
          background: current.background,
          color: current.color,
        }}
      >
        {current.icon}
      </div>

      <div>
        <p style={styles.summaryLabel}>{label}</p>

        <h2 style={styles.summaryValue}>{value}</h2>

        <p style={styles.summaryDescription}>
          {description}
        </p>
      </div>
    </div>
  );
}

/* =========================================================
   SEVERITY BADGE
========================================================= */

function SeverityBadge({ severity }) {
  const severityStyles = {
    CRITICAL: {
      background: "#fee2e2",
      color: "#b91c1c",
    },

    WARNING: {
      background: "#fef3c7",
      color: "#a16207",
    },

    INFO: {
      background: "#dbeafe",
      color: "#1d4ed8",
    },
  };

  return (
    <span
      style={{
        ...styles.severityBadge,
        ...severityStyles[severity],
      }}
    >
      {severity}
    </span>
  );
}

/* =========================================================
   STATUS BADGE
========================================================= */

function StatusBadge({ status }) {
  const isActive = status === "ACTIVE";

  return (
    <span
      style={{
        ...styles.statusBadge,
        background: isActive ? "#fef2f2" : "#f0fdf4",
        color: isActive ? "#b91c1c" : "#15803d",
      }}
    >
      {status}
    </span>
  );
}

/* =========================================================
   ALERT RULE
========================================================= */

function AlertRule({
  title,
  description,
  severity,
}) {
  return (
    <div style={styles.rule}>
      <div>
        <strong style={styles.ruleTitle}>
          {title}
        </strong>

        <p style={styles.ruleDescription}>
          {description}
        </p>
      </div>

      <SeverityBadge severity={severity} />
    </div>
  );
}

/* =========================================================
   STYLES
========================================================= */

const styles = {
  page: {
    minHeight: "100vh",
    background: "#f5f7fb",
    padding: "32px",
    color: "#172033",
    fontFamily:
      "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },

  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "30px",
  },

  overline: {
    margin: 0,
    fontSize: "12px",
    fontWeight: "700",
    letterSpacing: "1.5px",
    color: "#64748b",
  },

  title: {
    margin: "6px 0 5px",
    fontSize: "30px",
    fontWeight: "750",
  },

  subtitle: {
    margin: 0,
    color: "#64748b",
    fontSize: "14px",
  },

  liveBadge: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    padding: "8px 13px",
    borderRadius: "20px",
    background: "#ecfdf3",
    color: "#15803d",
    fontSize: "11px",
    fontWeight: "700",
  },

  liveDot: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    background: "#22c55e",
  },

  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "16px",
    marginBottom: "20px",
  },

  summaryCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "13px",
    padding: "20px",
    display: "flex",
    alignItems: "center",
    gap: "15px",
    boxShadow: "0 4px 14px rgba(15, 23, 42, 0.04)",
  },

  summaryIcon: {
    width: "42px",
    height: "42px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    fontSize: "17px",
  },

  summaryLabel: {
    margin: 0,
    fontSize: "10px",
    fontWeight: "700",
    color: "#64748b",
    letterSpacing: "0.8px",
  },

  summaryValue: {
    margin: "5px 0 2px",
    fontSize: "25px",
    fontWeight: "800",
  },

  summaryDescription: {
    margin: 0,
    color: "#94a3b8",
    fontSize: "11px",
  },

  panel: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "14px",
    overflow: "hidden",
    boxShadow: "0 4px 14px rgba(15, 23, 42, 0.04)",
    marginBottom: "20px",
  },

  panelHeader: {
    padding: "23px 25px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #eef2f7",
  },

  panelTitle: {
    margin: 0,
    fontSize: "18px",
  },

  panelDescription: {
    margin: "5px 0 0",
    color: "#64748b",
    fontSize: "12px",
  },

  filters: {
    display: "flex",
    gap: "6px",
  },

  filterButton: {
    border: "1px solid #e2e8f0",
    background: "#ffffff",
    color: "#64748b",
    padding: "8px 12px",
    borderRadius: "7px",
    fontSize: "10px",
    fontWeight: "700",
    cursor: "pointer",
  },

  activeFilter: {
    background: "#111827",
    color: "#ffffff",
    borderColor: "#111827",
  },

  tableContainer: {
    overflowX: "auto",
  },

  table: {
    width: "100%",
    borderCollapse: "collapse",
  },

  th: {
    padding: "13px 20px",
    textAlign: "left",
    fontSize: "10px",
    color: "#64748b",
    letterSpacing: "0.7px",
    fontWeight: "700",
    background: "#f8fafc",
    borderBottom: "1px solid #eef2f7",
  },

  td: {
    padding: "17px 20px",
    borderBottom: "1px solid #f1f5f9",
    fontSize: "13px",
  },

  tableRow: {
    transition: "background 0.15s ease",
  },

  time: {
    fontFamily: "monospace",
    color: "#475569",
    fontSize: "12px",
  },

  severityBadge: {
    display: "inline-block",
    padding: "5px 8px",
    borderRadius: "5px",
    fontSize: "9px",
    fontWeight: "800",
    letterSpacing: "0.4px",
  },

  statusBadge: {
    display: "inline-block",
    padding: "5px 8px",
    borderRadius: "5px",
    fontSize: "9px",
    fontWeight: "800",
  },

  message: {
    fontWeight: "600",
    color: "#334155",
  },

  source: {
    color: "#64748b",
  },

  emptyState: {
    textAlign: "center",
    padding: "50px",
    color: "#94a3b8",
    fontSize: "13px",
  },

  bottomGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
    marginBottom: "20px",
  },

  activityCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: "14px",
    padding: "23px",
  },

  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "18px",
  },

  cardTitle: {
    margin: 0,
    fontSize: "17px",
  },

  cardDescription: {
    margin: "5px 0 0",
    color: "#64748b",
    fontSize: "12px",
  },

  criticalIcon: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    background: "#fee2e2",
    color: "#b91c1c",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
  },

  criticalEvent: {
    display: "flex",
    gap: "12px",
    padding: "14px 0",
    borderBottom: "1px solid #f1f5f9",
  },

  eventDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: "#ef4444",
    marginTop: "6px",
    flexShrink: 0,
  },

  eventMessage: {
    fontSize: "13px",
  },

  eventMeta: {
    margin: "4px 0 0",
    fontSize: "11px",
    color: "#94a3b8",
  },

  noCritical: {
    color: "#94a3b8",
    fontSize: "13px",
  },

  rule: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 0",
    borderBottom: "1px solid #f1f5f9",
    gap: "15px",
  },

  ruleTitle: {
    fontSize: "13px",
  },

  ruleDescription: {
    margin: "4px 0 0",
    fontSize: "11px",
    color: "#94a3b8",
  },

  infoBox: {
    display: "flex",
    gap: "13px",
    padding: "17px",
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    borderRadius: "11px",
  },

  infoIcon: {
    width: "28px",
    height: "28px",
    flexShrink: 0,
    borderRadius: "50%",
    background: "#3b82f6",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    fontSize: "13px",
  },

  infoTitle: {
    margin: "2px 0 4px",
    fontSize: "13px",
    color: "#1e40af",
  },

  infoText: {
    margin: 0,
    fontSize: "11px",
    lineHeight: "1.5",
    color: "#1e40af",
  },
};