import { useState } from "react";

export default function LoadTesting() {
  const [running, setRunning] = useState(false);
  const [testCompleted, setTestCompleted] = useState(false);

  const [config, setConfig] = useState({
    virtualUsers: 1000,
    duration: 60,
    rampUp: 30,
    targetUrl: "http://localhost:3000",
  });

  const [result, setResult] = useState({
    requests: 0,
    successRate: 0,
    avgResponse: 0,
    p95Response: 0,
    peakUsers: 0,
    errors: 0,
  });

  const startTest = () => {
    setRunning(true);
    setTestCompleted(false);

    setResult({
      requests: 0,
      successRate: 0,
      avgResponse: 0,
      p95Response: 0,
      peakUsers: 0,
      errors: 0,
    });

    // Demo UI behavior only.
    // Real k6 execution should be handled by the backend/load-test service.
    setTimeout(() => {
      setRunning(false);
      setTestCompleted(true);

      setResult({
        requests: 58420,
        successRate: 99.8,
        avgResponse: 184,
        p95Response: 420,
        peakUsers: Number(config.virtualUsers),
        errors: 117,
      });
    }, 2000);
  };

  const stopTest = () => {
    setRunning(false);
  };

  const handleChange = (field, value) => {
    setConfig((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const statusText = running
    ? "Test Running"
    : testCompleted
    ? "Completed"
    : "Ready";

  return (
    <div style={styles.page}>
      {/* Header */}
      <div style={styles.header}>
        <div>
          <div style={styles.breadcrumb}>Admin / Load Testing</div>
          <h1 style={styles.title}>Load Testing</h1>
          <p style={styles.subtitle}>
            Validate FairQueue performance under high concurrent traffic.
          </p>
        </div>

        <div style={styles.headerStatus}>
          <span
            style={{
              ...styles.statusDot,
              background: running
                ? "#f59e0b"
                : testCompleted
                ? "#22c55e"
                : "#64748b",
            }}
          />
          {statusText}
        </div>
      </div>

      {/* Warning */}
      <div style={styles.infoBox}>
        <div style={styles.infoIcon}>i</div>
        <div>
          <strong style={styles.infoTitle}>Load Test Environment</strong>
          <p style={styles.infoText}>
            Use a controlled environment when running high-concurrency tests.
            Real k6 execution and production metrics should come from the
            backend load-testing service.
          </p>
        </div>
      </div>

      {/* Main Grid */}
      <div style={styles.mainGrid}>
        {/* Configuration */}
        <section style={styles.card}>
          <div style={styles.cardHeader}>
            <div>
              <h2 style={styles.cardTitle}>Test Configuration</h2>
              <p style={styles.cardSubtitle}>
                Configure the traffic pattern for the test.
              </p>
            </div>
          </div>

          <div style={styles.formGrid}>
            <div style={styles.formGroup}>
              <label style={styles.label}>Virtual Users</label>

              <input
                type="number"
                min="1"
                value={config.virtualUsers}
                disabled={running}
                onChange={(e) =>
                  handleChange("virtualUsers", Number(e.target.value))
                }
                style={styles.input}
              />

              <span style={styles.helper}>
                Maximum concurrent users generated by the test.
              </span>
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Duration</label>

              <div style={styles.inputWithSuffix}>
                <input
                  type="number"
                  min="1"
                  value={config.duration}
                  disabled={running}
                  onChange={(e) =>
                    handleChange("duration", Number(e.target.value))
                  }
                  style={styles.inputNoBorder}
                />
                <span style={styles.suffix}>seconds</span>
              </div>

              <span style={styles.helper}>
                Total duration of the load test.
              </span>
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Ramp Up</label>

              <div style={styles.inputWithSuffix}>
                <input
                  type="number"
                  min="1"
                  value={config.rampUp}
                  disabled={running}
                  onChange={(e) =>
                    handleChange("rampUp", Number(e.target.value))
                  }
                  style={styles.inputNoBorder}
                />
                <span style={styles.suffix}>seconds</span>
              </div>

              <span style={styles.helper}>
                Time taken to reach maximum users.
              </span>
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Target URL</label>

              <input
                type="text"
                value={config.targetUrl}
                disabled={running}
                onChange={(e) =>
                  handleChange("targetUrl", e.target.value)
                }
                style={styles.input}
              />

              <span style={styles.helper}>
                API or application endpoint used for testing.
              </span>
            </div>
          </div>

          {/* Scenario */}
          <div style={styles.scenario}>
            <div style={styles.scenarioHeader}>
              <div>
                <h3 style={styles.scenarioTitle}>FairQueue Stress Scenario</h3>
                <p style={styles.scenarioDescription}>
                  Simulates a large number of users entering the ticket
                  booking flow simultaneously.
                </p>
              </div>

              <span style={styles.scenarioBadge}>High Concurrency</span>
            </div>

            <div style={styles.flow}>
              <FlowStep number="01" title="Users" />
              <FlowArrow />
              <FlowStep number="02" title="Load Balancer" />
              <FlowArrow />
              <FlowStep number="03" title="Rate Check" />
              <FlowArrow />
              <FlowStep number="04" title="Redis Queue" />
              <FlowArrow />
              <FlowStep number="05" title="Admission" />
              <FlowArrow />
              <FlowStep number="06" title="Booking" />
            </div>
          </div>

          {/* Buttons */}
          <div style={styles.actions}>
            {!running ? (
              <button style={styles.primaryButton} onClick={startTest}>
                ▶ Start Load Test
              </button>
            ) : (
              <button style={styles.stopButton} onClick={stopTest}>
                ■ Stop Test
              </button>
            )}

            <button
              style={styles.secondaryButton}
              disabled={running}
              onClick={() => {
                setTestCompleted(false);
                setResult({
                  requests: 0,
                  successRate: 0,
                  avgResponse: 0,
                  p95Response: 0,
                  peakUsers: 0,
                  errors: 0,
                });
              }}
            >
              Reset
            </button>
          </div>
        </section>

        {/* Test Summary */}
        <section style={styles.card}>
          <div style={styles.cardHeader}>
            <div>
              <h2 style={styles.cardTitle}>Test Summary</h2>
              <p style={styles.cardSubtitle}>
                Current load-test execution status.
              </p>
            </div>
          </div>

          <div style={styles.summaryList}>
            <SummaryRow
              label="Status"
              value={statusText}
              valueStyle={
                running
                  ? styles.warningText
                  : testCompleted
                  ? styles.successText
                  : styles.neutralText
              }
            />

            <SummaryRow
              label="Virtual Users"
              value={config.virtualUsers.toLocaleString()}
            />

            <SummaryRow
              label="Duration"
              value={`${config.duration}s`}
            />

            <SummaryRow
              label="Ramp Up"
              value={`${config.rampUp}s`}
            />

            <SummaryRow
              label="Target"
              value={config.targetUrl}
            />
          </div>

          <div style={styles.performanceNote}>
            <strong>What this test validates</strong>

            <ul style={styles.list}>
              <li>Concurrent request handling</li>
              <li>Queue admission behaviour</li>
              <li>Response time under load</li>
              <li>Backend error rate</li>
              <li>Inventory protection</li>
            </ul>
          </div>
        </section>
      </div>

      {/* Results */}
      <section style={styles.card}>
        <div style={styles.cardHeader}>
          <div>
            <h2 style={styles.cardTitle}>Performance Results</h2>
            <p style={styles.cardSubtitle}>
              Metrics returned by the latest test execution.
            </p>
          </div>

          {testCompleted && (
            <span style={styles.completedBadge}>Completed</span>
          )}
        </div>

        <div style={styles.metricsGrid}>
          <MetricCard
            title="Total Requests"
            value={
              result.requests
                ? result.requests.toLocaleString()
                : "—"
            }
            description="Requests generated"
          />

          <MetricCard
            title="Success Rate"
            value={
              result.successRate
                ? `${result.successRate}%`
                : "—"
            }
            description="Successful requests"
          />

          <MetricCard
            title="Avg Response"
            value={result.avgResponse ? `${result.avgResponse} ms` : "—"}
            description="Average response time"
          />

          <MetricCard
            title="P95 Response"
            value={
              result.p95Response
                ? `${result.p95Response} ms`
                : "—"
            }
            description="95th percentile"
          />

          <MetricCard
            title="Peak Users"
            value={
              result.peakUsers
                ? result.peakUsers.toLocaleString()
                : "—"
            }
            description="Maximum concurrent users"
          />

          <MetricCard
            title="Errors"
            value={
              result.errors
                ? result.errors.toLocaleString()
                : "—"
            }
            description="Failed requests"
          />
        </div>
      </section>

      {/* Load Test Checklist */}
      <section style={styles.card}>
        <div style={styles.cardHeader}>
          <div>
            <h2 style={styles.cardTitle}>Validation Checklist</h2>
            <p style={styles.cardSubtitle}>
              Items to verify after a real load-test execution.
            </p>
          </div>
        </div>

        <div style={styles.checklist}>
          <CheckItem
            title="No Overselling"
            description="Inventory should never become negative."
          />

          <CheckItem
            title="Controlled Admission"
            description="Only configured users should enter the booking stage."
          />

          <CheckItem
            title="Queue Stability"
            description="Waiting users should remain ordered and recoverable."
          />

          <CheckItem
            title="Hold Expiration"
            description="Expired ticket holds should return to inventory."
          />

          <CheckItem
            title="Idempotent Checkout"
            description="Repeated checkout requests should not create duplicate orders."
          />

          <CheckItem
            title="System Recovery"
            description="The system should recover correctly after traffic decreases."
          />
        </div>
      </section>

      {/* Architecture */}
      <section style={styles.card}>
        <div style={styles.cardHeader}>
          <div>
            <h2 style={styles.cardTitle}>Load Test Architecture</h2>
            <p style={styles.cardSubtitle}>
              Recommended request path for FairQueue.
            </p>
          </div>
        </div>

        <div style={styles.architecture}>
          <ArchitectureNode title="k6" subtitle="Traffic Generator" />
          <ArchitectureArrow />

          <ArchitectureNode
            title="Load Balancer"
            subtitle="Traffic Distribution"
          />
          <ArchitectureArrow />

          <ArchitectureNode
            title="FairQueue API"
            subtitle="Application Layer"
          />
          <ArchitectureArrow />

          <ArchitectureNode
            title="Redis"
            subtitle="Queue / Admission"
          />
          <ArchitectureArrow />

          <ArchitectureNode
            title="MongoDB"
            subtitle="Inventory / Orders"
          />
        </div>
      </section>
    </div>
  );
}

/* ---------------- Components ---------------- */

function FlowStep({ number, title }) {
  return (
    <div style={styles.flowStep}>
      <div style={styles.flowNumber}>{number}</div>
      <div style={styles.flowTitle}>{title}</div>
    </div>
  );
}

function FlowArrow() {
  return <div style={styles.flowArrow}>→</div>;
}

function SummaryRow({ label, value, valueStyle }) {
  return (
    <div style={styles.summaryRow}>
      <span style={styles.summaryLabel}>{label}</span>
      <span style={{ ...styles.summaryValue, ...valueStyle }}>
        {value}
      </span>
    </div>
  );
}

function MetricCard({ title, value, description }) {
  return (
    <div style={styles.metricCard}>
      <span style={styles.metricTitle}>{title}</span>

      <strong style={styles.metricValue}>{value}</strong>

      <span style={styles.metricDescription}>{description}</span>
    </div>
  );
}

function CheckItem({ title, description }) {
  return (
    <div style={styles.checkItem}>
      <div style={styles.checkIcon}>✓</div>

      <div>
        <strong style={styles.checkTitle}>{title}</strong>
        <p style={styles.checkDescription}>{description}</p>
      </div>
    </div>
  );
}

function ArchitectureNode({ title, subtitle }) {
  return (
    <div style={styles.architectureNode}>
      <strong style={styles.architectureTitle}>{title}</strong>
      <span style={styles.architectureSubtitle}>{subtitle}</span>
    </div>
  );
}

function ArchitectureArrow() {
  return <div style={styles.architectureArrow}>→</div>;
}

/* ---------------- Styles ---------------- */

const styles = {
  page: {
    minHeight: "100vh",
    background: "#f8fafc",
    padding: "32px",
    color: "#0f172a",
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },

  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "20px",
    marginBottom: "28px",
  },

  breadcrumb: {
    color: "#64748b",
    fontSize: "13px",
    fontWeight: "600",
    marginBottom: "8px",
  },

  title: {
    margin: 0,
    fontSize: "30px",
    fontWeight: "800",
    letterSpacing: "-0.6px",
  },

  subtitle: {
    margin: "8px 0 0",
    color: "#64748b",
    fontSize: "14px",
  },

  headerStatus: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 14px",
    border: "1px solid #e2e8f0",
    background: "#ffffff",
    borderRadius: "10px",
    fontSize: "13px",
    fontWeight: "700",
  },

  statusDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    display: "inline-block",
  },

  infoBox: {
    display: "flex",
    gap: "14px",
    padding: "16px 18px",
    marginBottom: "24px",
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    borderRadius: "12px",
  },

  infoIcon: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    background: "#2563eb",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "13px",
    fontWeight: "800",
    flexShrink: 0,
  },

  infoTitle: {
    display: "block",
    fontSize: "14px",
    marginBottom: "4px",
  },

  infoText: {
    margin: 0,
    color: "#475569",
    fontSize: "13px",
    lineHeight: "1.6",
  },

  mainGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 2fr) minmax(300px, 1fr)",
    gap: "24px",
    marginBottom: "24px",
  },

  card: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: "14px",
    padding: "24px",
    marginBottom: "24px",
    boxShadow: "0 1px 2px rgba(15, 23, 42, 0.03)",
  },

  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    marginBottom: "22px",
  },

  cardTitle: {
    margin: 0,
    fontSize: "18px",
    fontWeight: "800",
  },

  cardSubtitle: {
    margin: "6px 0 0",
    color: "#64748b",
    fontSize: "13px",
  },

  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "20px",
  },

  formGroup: {
    display: "flex",
    flexDirection: "column",
  },

  label: {
    fontSize: "13px",
    fontWeight: "700",
    marginBottom: "8px",
  },

  input: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #cbd5e1",
    borderRadius: "9px",
    padding: "11px 12px",
    fontSize: "14px",
    outline: "none",
    background: "#ffffff",
    color: "#0f172a",
  },

  inputWithSuffix: {
    display: "flex",
    alignItems: "center",
    border: "1px solid #cbd5e1",
    borderRadius: "9px",
    overflow: "hidden",
    background: "#ffffff",
  },

  inputNoBorder: {
    width: "100%",
    boxSizing: "border-box",
    border: "none",
    outline: "none",
    padding: "11px 12px",
    fontSize: "14px",
    color: "#0f172a",
  },

  suffix: {
    padding: "0 12px",
    color: "#64748b",
    fontSize: "12px",
    borderLeft: "1px solid #e2e8f0",
    whiteSpace: "nowrap",
  },

  helper: {
    color: "#94a3b8",
    fontSize: "11px",
    marginTop: "6px",
    lineHeight: "1.4",
  },

  scenario: {
    marginTop: "24px",
    padding: "18px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
  },

  scenarioHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "16px",
  },

  scenarioTitle: {
    margin: 0,
    fontSize: "15px",
    fontWeight: "800",
  },

  scenarioDescription: {
    margin: "5px 0 0",
    color: "#64748b",
    fontSize: "12px",
    lineHeight: "1.5",
  },

  scenarioBadge: {
    background: "#ede9fe",
    color: "#6d28d9",
    padding: "6px 9px",
    borderRadius: "7px",
    fontSize: "10px",
    fontWeight: "800",
    whiteSpace: "nowrap",
  },

  flow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    overflowX: "auto",
    marginTop: "20px",
    paddingBottom: "4px",
  },

  flowStep: {
    minWidth: "88px",
    textAlign: "center",
  },

  flowNumber: {
    width: "28px",
    height: "28px",
    margin: "0 auto 7px",
    borderRadius: "50%",
    background: "#0f172a",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "9px",
    fontWeight: "800",
  },

  flowTitle: {
    color: "#334155",
    fontSize: "10px",
    fontWeight: "700",
    whiteSpace: "nowrap",
  },

  flowArrow: {
    color: "#94a3b8",
    fontSize: "18px",
    flexShrink: 0,
  },

  actions: {
    display: "flex",
    gap: "10px",
    marginTop: "24px",
  },

  primaryButton: {
    border: "none",
    borderRadius: "9px",
    padding: "11px 16px",
    background: "#0f172a",
    color: "#ffffff",
    fontSize: "13px",
    fontWeight: "700",
    cursor: "pointer",
  },

  stopButton: {
    border: "none",
    borderRadius: "9px",
    padding: "11px 16px",
    background: "#dc2626",
    color: "#ffffff",
    fontSize: "13px",
    fontWeight: "700",
    cursor: "pointer",
  },

  secondaryButton: {
    border: "1px solid #cbd5e1",
    borderRadius: "9px",
    padding: "11px 16px",
    background: "#ffffff",
    color: "#334155",
    fontSize: "13px",
    fontWeight: "700",
    cursor: "pointer",
  },

  summaryList: {
    borderTop: "1px solid #e2e8f0",
  },

  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "16px",
    padding: "13px 0",
    borderBottom: "1px solid #e2e8f0",
  },

  summaryLabel: {
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "600",
  },

  summaryValue: {
    color: "#0f172a",
    fontSize: "12px",
    fontWeight: "800",
    textAlign: "right",
    wordBreak: "break-word",
  },

  successText: {
    color: "#16a34a",
  },

  warningText: {
    color: "#d97706",
  },

  neutralText: {
    color: "#64748b",
  },

  performanceNote: {
    marginTop: "20px",
    padding: "15px",
    background: "#f8fafc",
    borderRadius: "9px",
    border: "1px solid #e2e8f0",
  },

  list: {
    margin: "10px 0 0",
    paddingLeft: "18px",
    color: "#64748b",
    fontSize: "12px",
    lineHeight: "1.9",
  },

  completedBadge: {
    padding: "7px 10px",
    borderRadius: "7px",
    background: "#dcfce7",
    color: "#15803d",
    fontSize: "11px",
    fontWeight: "800",
  },

  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: "14px",
  },

  metricCard: {
    border: "1px solid #e2e8f0",
    borderRadius: "11px",
    padding: "16px",
    minHeight: "105px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },

  metricTitle: {
    color: "#64748b",
    fontSize: "11px",
    fontWeight: "700",
  },

  metricValue: {
    fontSize: "23px",
    fontWeight: "800",
    color: "#0f172a",
    margin: "8px 0",
  },

  metricDescription: {
    color: "#94a3b8",
    fontSize: "10px",
  },

  checklist: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "14px",
  },

  checkItem: {
    display: "flex",
    gap: "12px",
    padding: "15px",
    border: "1px solid #e2e8f0",
    borderRadius: "10px",
  },

  checkIcon: {
    width: "25px",
    height: "25px",
    borderRadius: "50%",
    background: "#dcfce7",
    color: "#15803d",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    fontWeight: "900",
    flexShrink: 0,
  },

  checkTitle: {
    fontSize: "13px",
    display: "block",
  },

  checkDescription: {
    margin: "5px 0 0",
    color: "#64748b",
    fontSize: "11px",
    lineHeight: "1.5",
  },

  architecture: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    overflowX: "auto",
    padding: "10px 0",
  },

  architectureNode: {
    minWidth: "135px",
    padding: "15px 12px",
    border: "1px solid #cbd5e1",
    borderRadius: "10px",
    background: "#f8fafc",
    textAlign: "center",
  },

  architectureTitle: {
    display: "block",
    fontSize: "12px",
    fontWeight: "800",
  },

  architectureSubtitle: {
    display: "block",
    color: "#64748b",
    fontSize: "9px",
    marginTop: "5px",
  },

  architectureArrow: {
    color: "#94a3b8",
    fontSize: "20px",
    flexShrink: 0,
  },
};